# Generated by Django 5.0.6 on 2024-06-10 20:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="static/default.jpg",
                        null=True,
                        upload_to="static/",
                    ),
                ),
                ("breed", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")], max_length=1
                    ),
                ),
                (
                    "date_of_next_service",
                    models.DateField(
                        blank=True, help_text="Only applicable for female", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIPredeterminedServiced",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_service",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("female", "Female")], default="female", max_length=10
                    ),
                ),
                (
                    "date_of_next_service",
                    models.DateField(
                        blank=True, help_text="only applicable for female", null=True
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animal.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AInotPredeterminedServiced",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_service",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("birth_date", models.DateField(max_length=50)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animal.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocallyServiced",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_owner", models.CharField(max_length=50)),
                (
                    "date_of_service",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("birth_date", models.DateField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animal.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchased",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller_name", models.CharField(max_length=50)),
                ("date_purchased", models.DateField(default=django.utils.timezone.now)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animal.animal"
                    ),
                ),
            ],
        ),
    ]
