# Generated by Django 5.0.6 on 2024-07-01 20:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AInonPredeterminedServiceAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_name",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="static/default.jpg", upload_to="static/"
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")], max_length=1
                    ),
                ),
                (
                    "date_of_next_service",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Only applicable for female",
                    ),
                ),
                (
                    "date_of_service",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "birth_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIPredeterminedServiceAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_name",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="static/default.jpg", upload_to="static/"
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")],
                        default="female",
                        max_length=1,
                    ),
                ),
                (
                    "date_of_next_service",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="only applicable for female",
                    ),
                ),
                (
                    "date_of_service",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "birth_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocallyServicedAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_name",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="static/default.jpg", upload_to="static/"
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")], max_length=1
                    ),
                ),
                (
                    "date_of_next_service",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Only applicable for female",
                    ),
                ),
                (
                    "name_of_owner",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "date_of_service",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "birth_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_name",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="static/default.jpg", upload_to="static/"
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")], max_length=1
                    ),
                ),
                (
                    "date_of_next_service",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Only applicable for female",
                    ),
                ),
                (
                    "seller_name",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "date_purchased",
                    models.DateField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
