# Generated by Django 5.0.6 on 2024-06-24 10:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                ("id", models.AutoField(default=1, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="static/default.jpg",
                        null=True,
                        upload_to="static/",
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")], max_length=1
                    ),
                ),
                (
                    "date_of_next_service",
                    models.DateField(
                        blank=True, help_text="Only applicable for female", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("purchased", "Purchased"),
                            ("locally_serviced", "Locally Serviced"),
                            ("ai_predetermined", "AI Predetermined"),
                            ("ai_non_predetermined", "AI not Predetermined"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIPredeterminedServiceAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_service",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("birth_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "gender",
                    models.CharField(
                        choices=[("female", "Female")], default="female", max_length=10
                    ),
                ),
                (
                    "date_of_next_service",
                    models.DateField(
                        blank=True, help_text="only applicable for female", null=True
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animal.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AInonPredeterminedServiceAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_service",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("birth_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animal.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dosagetreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_diagnosis",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "name_of_vet",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "date_of_medicine_treatment",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "dosage_treatment_used",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[("D", "dead"), ("C", "cured")], max_length=1
                    ),
                ),
                (
                    "cured",
                    models.CharField(
                        choices=[("S", "sold"), ("N", "not sold")], max_length=1
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animal.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocallyServiced",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_of_owner",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "date_of_service",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("birth_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animal.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_diagnosis",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "name_of_vet",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2,
                                message="Name of vet must be at least 2 characters long.",
                            )
                        ],
                    ),
                ),
                (
                    "date_of_medicine_treatment",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[("D", "dead"), ("C", "cured")], max_length=1
                    ),
                ),
                (
                    "cured",
                    models.CharField(
                        choices=[("S", "sold"), ("N", "not sold")], max_length=1
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animal.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchased",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller_name",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("date_purchased", models.DateField(default=django.utils.timezone.now)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animal.animal"
                    ),
                ),
            ],
        ),
    ]
