# Generated by Django 5.0.6 on 2024-07-01 21:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPredeterminedAndNonPredeterminedServiceAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_name",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="static/default.jpg", upload_to="static/"
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")],
                        default="female",
                        max_length=1,
                    ),
                ),
                (
                    "date_of_next_service",
                    models.DateField(
                        default=datetime.datetime(
                            2024, 7, 1, 21, 3, 33, 926064, tzinfo=datetime.timezone.utc
                        ),
                        help_text="only applicable for female",
                        null=True,
                    ),
                ),
                (
                    "date_of_service",
                    models.DateField(
                        default=datetime.datetime(
                            2024, 7, 1, 21, 3, 33, 927080, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        default=datetime.datetime(
                            2024, 7, 1, 21, 3, 33, 927080, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AInonPredeterminedServiceAnimal",
        ),
        migrations.DeleteModel(
            name="AIPredeterminedServiceAnimal",
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 1, 21, 3, 33, 925050, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="date_of_next_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 1, 21, 3, 33, 924535, tzinfo=datetime.timezone.utc
                ),
                help_text="Only applicable for female",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 1, 21, 3, 33, 925050, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_of_next_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 1, 21, 3, 33, 922303, tzinfo=datetime.timezone.utc
                ),
                help_text="Only applicable for female",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_purchased",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 1, 21, 3, 33, 922816, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
