# Generated by Django 5.0.6 on 2024-08-27 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 33, 517888, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 33, 517916, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 33, 517905, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 33, 517560, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 33, 517592, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 33, 517581, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 33, 517188, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 33, 517236, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 33, 517207, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 33, 516713, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_purchased",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 33, 516766, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 33, 516734, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
