# Generated by Django 5.0.6 on 2024-06-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0002_treatmentrecords_medicinetreatment_dosagetreatment"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="source",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("locally_serviced", "Locally Serviced"),
                    ("ai_predetermined", "AI Predetermined"),
                    ("ai_not_predetermined", "AI not Predetermined"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
