# Generated by Django 5.0.6 on 2024-08-27 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0002_alter_ainonpredeterminedservicedanimal_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 43, 224856, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 43, 224884, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 43, 224873, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 43, 224517, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 43, 224548, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 43, 224538, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 43, 224110, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 43, 224159, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 43, 224129, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 43, 223588, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_purchased",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 43, 223652, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 13, 49, 43, 223616, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
