# Generated by Django 5.0.6 on 2024-06-23 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0003_animal_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locallyserviced",
            name="birth_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
