# Generated by Django 5.0.6 on 2024-06-23 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0004_alter_locallyserviced_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ainotpredeterminedserviced",
            name="birth_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviced",
            name="birth_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
