# Generated by Django 5.0.6 on 2024-09-24 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0004_alter_disposal_date_of_disposal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposal",
            name="date_of_disposal",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 9, 24, 23, 58, 37, 42054, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 9, 24, 23, 58, 37, 40842, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 9, 24, 23, 58, 37, 40857, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 9, 24, 23, 58, 37, 40498, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_purchased",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 9, 24, 23, 58, 37, 40554, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 9, 24, 23, 58, 37, 40517, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="servingbase",
            name="date_presented",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 9, 24, 23, 58, 37, 42331, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="servingbase",
            name="expected_date_of_delivery",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 9, 24, 23, 58, 37, 42362, tzinfo=datetime.timezone.utc
                ),
                help_text="Only applicable if status is confirmed.",
                null=True,
            ),
        ),
    ]
