# Generated by Django 5.0.6 on 2024-08-27 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0004_alter_ainonpredeterminedservicedanimal_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 14, 1, 41, 345276, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 14, 1, 41, 345301, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 14, 1, 41, 345291, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 14, 1, 41, 344995, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 14, 1, 41, 345021, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 14, 1, 41, 345012, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 14, 1, 41, 344680, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 14, 1, 41, 344720, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 14, 1, 41, 344696, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 14, 1, 41, 344259, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_purchased",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 14, 1, 41, 344306, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="expected_maturity_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 27, 14, 1, 41, 344279, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
