# Generated by Django 5.0.6 on 2024-07-22 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0006_alter_ainonpredeterminedservicedanimal_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 12, 25, 49, 893833, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 12, 25, 49, 893804, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 12, 25, 49, 893308, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 12, 25, 49, 893276, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 12, 25, 49, 892751, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 12, 25, 49, 892725, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_purchased",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 12, 25, 49, 891742, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
