# Generated by Django 5.0.6 on 2024-07-22 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0007_alter_ainonpredeterminedservicedanimal_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 13, 11, 3, 189723, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 13, 11, 3, 189695, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 13, 11, 3, 189224, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 13, 11, 3, 189193, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 13, 11, 3, 188673, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 13, 11, 3, 188647, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_purchased",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 13, 11, 3, 187759, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
