# Generated by Django 5.0.6 on 2024-08-06 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0018_dosagetreatment_dosage_treatment_used_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 14, 35, 623641, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 14, 35, 623622, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 14, 35, 623273, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 14, 35, 623258, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="dosagetreatment",
            name="date_of_diagnosis",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 14, 35, 624440, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="dosagetreatment",
            name="date_of_medication",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 14, 35, 624487, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 14, 35, 622905, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 14, 35, 622889, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="medicinetreatment",
            name="date_of_diagnosis",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 14, 35, 623985, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="medicinetreatment",
            name="date_of_medication",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 14, 35, 624018, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_purchased",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 14, 35, 622528, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
