# Generated by Django 5.0.6 on 2024-08-06 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0019_alter_ainonpredeterminedservicedanimal_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 54, 5, 876411, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="ainonpredeterminedservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 54, 5, 876392, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 54, 5, 876064, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="aipredeterminedserviceanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 54, 5, 876048, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="dosagetreatment",
            name="date_of_diagnosis",
            field=models.DateField(default=datetime.date(2024, 8, 6)),
        ),
        migrations.AlterField(
            model_name="dosagetreatment",
            name="date_of_medication",
            field=models.DateField(default=datetime.date(2024, 8, 6)),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 54, 5, 875693, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="locallyservicedanimal",
            name="date_of_service",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 54, 5, 875677, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="medicinetreatment",
            name="date_of_diagnosis",
            field=models.DateField(default=datetime.date(2024, 8, 6)),
        ),
        migrations.AlterField(
            model_name="medicinetreatment",
            name="date_of_medication",
            field=models.DateField(default=datetime.date(2024, 8, 6)),
        ),
        migrations.AlterField(
            model_name="purchasedanimal",
            name="date_purchased",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 20, 54, 5, 875296, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
